# Day 12 ( Part - 1 )
# Numpy


In [3]:
import numpy as np

In [4]:
arr = np.array({1,2,3,4,5,6,})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>


# using a tupple to create a numpy

In [8]:
print(arr)
print(type(arr))

{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>


# dimension in array

In [11]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


# 1d array

In [12]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1


# 2d array

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


# 3d array

In [19]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3


# Creating a 5 dimension array

In [8]:
import numpy as np 
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("number of the dimension is : ", arr.ndim)


[[[[[1 2 3 4]]]]]
number of the dimension is :  5


# Numpy Array Indexing

In [9]:
arr = ([1,2,3,4,5])
print(arr[0])

1


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element on the 1st row : ", arr[0,1])

2nd element on the 1st row :  2


In [13]:
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element on the 2nd row : ", arr[1,1])

2nd element on the 2nd row :  5


# add the first element of row 1 and last element 

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print("First element of row 1 :", arr[0,0])
print("First element of row 2 ", arr[1,2])
print("sum of both the element is : ", arr [0,0]+arr[1,2])

First element of row 1 : 1
First element of row 2  6
sum of both the element is :  7


# Accessinng the 3 -D arrays

In [21]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0,1,2])

6
