# Day 13 
# Numpy part 2
# slicing of the numpy arrays

In [1]:
 import numpy as np

In [3]:
arr  = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


In [6]:
arr  = np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


# slicing of 2d arrays

In [10]:
arr  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])
print(arr)
print(arr[1,1:4])

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]
[8 7 6]


In [11]:
arr  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])
print(arr)
print(arr[0,1:4])

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]
[2 3 4]


# Data types in Numpy
Numpy has some extra data teypes and refer to data types with one character.
    i = integer
    b = boolen
    u = unsigned integer
    f = float
    c = complex float
    m = timedelta
    M = datetime
    O = object
    s = string
    U = unicode string
    V = Fixed chuck of memory for other type (void})

# checking the data type of data type 

In [14]:
arr  = np.array([1,2,3,4,5,6,7,8,9])
print(arr.dtype)

int32


In [15]:
arr  = np.array(["animals", 'cat', ' dog'])
print(arr.dtype)

<U7


# creating arrays with a defied data type

In [18]:
arr = np.array([1,2,3,4,5,6,7], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
|S1


# Create and array with data types 4 bytese integer

In [20]:
arr = np.array([1,2,3,4,5,6,7], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7]
int32


# Numpy array shape

the shape of on array is the number of elements in each diimension

# print the shape of 2d array

In [23]:
arr  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])
print(arr.shape)

(2, 9)


In [27]:
arr  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1], [10,20,30,40,50,60,70,80,90,]])
print(arr.shape)

(3, 9)


# joining Numpy Arrays

In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 3 4 5]


# joining 2 d array

In [32]:
arr1  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])
arr2  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])

arr= np.concatenate((arr1,arr2), axis = 1)
print(arr)

[[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1 9 8 7 6 5 4 3 2 1]]


In [33]:
arr1  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])
arr2  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])

arr= np.concatenate((arr1,arr2), axis = 0)
print(arr)

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]
 [1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]


 # Splitting Numpy arrays 

In [36]:
arr  = np.array([1,2,3,4,5,6,7,8,9])

newarr = np.array_split(arr,2)
print(newarr)


[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]


In [38]:
arr  = np.array([1,2,3,4,5,6,7,8,9])

newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# ravel & Flatten

In [39]:
# converts multidimensional array into 1 ad array 

In [52]:
arr  = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1], [10,20,30,40,50,60,70,80,90,]])
print(arr)
print('The current dimension of array is :',arr.ndim)
n = arr.ravel()
print(n)
print('The new dimension of array is :',n.ndim)

[[ 1  2  3  4  5  6  7  8  9]
 [ 9  8  7  6  5  4  3  2  1]
 [10 20 30 40 50 60 70 80 90]]
The current dimension of array is : 2
[ 1  2  3  4  5  6  7  8  9  9  8  7  6  5  4  3  2  1 10 20 30 40 50 60
 70 80 90]
The new dimension of array is : 1


# Unique function 

In [53]:
f = np.array ([12,5,84,65,32,654,321,6,1,1,32,32,6,21,21,54,51,])
print(f)
x = np.unique(f)
print (x)

[ 12   5  84  65  32 654 321   6   1   1  32  32   6  21  21  54  51]
[  1   5   6  12  21  32  51  54  65  84 321 654]


In [55]:
f = np.array ([12,5,84,65,32,654,321,6,1,1,32,32,6,21,21,54,51,])
print(f)
x = np.unique(f, return_index = True, return_counts= True)
print (x)

[ 12   5  84  65  32 654 321   6   1   1  32  32   6  21  21  54  51]
(array([  1,   5,   6,  12,  21,  32,  51,  54,  65,  84, 321, 654]), array([ 8,  1,  7,  0, 13,  4, 16, 15,  3,  2,  6,  5]), array([2, 1, 2, 1, 2, 3, 1, 1, 1, 1, 1, 1]))


# using delete function

In [57]:
f = np.array ([12,5,84,65,32,654,321,6,1,1,32,32,6,21,21,54,51,])
d = np.delete(f, [1])
print(d)

[ 12  84  65  32 654 321   6   1   1  32  32   6  21  21  54  51]
